### ISSUE TITLE
A note for future docs re: the bundle command

### ISSUE THREAD

**Issue by 5t3ph** [11ty/demo-eleventy-serverless#1]
Hey Zach!

This is sooooo awesome, very pumped about this being a thing!

I just wanted to note that in trying this, I needed to use `sh ./bundle.sh` as the script command. 

It took quite a bit of searching to figure out that's what my issue was, but it had to do with making sure that script didn't care about it's own file permissions I guess? Without that tweak it didn't work for me locally (Mac, using VSCode zsh terminal) _or_ when I test deployed to Netlify.

For complete reference, the error was:

```
sh: ./bundle.sh: Permission denied
ERROR: "bundle" exited with 126.
```

Thanks!

**Comment by zachleat** [comment]
Ah, nice thank you! Before I’d consider this “ready for primetime” I will want to iterate to a point where `bundle.sh` goes away and is replaced by some automated passthrough copy though

**Comment by zachleat** [comment]
Hey, the bundle script went away with the new version! It’s all in the plugin now.
